import mongoose from 'mongoose';

const creditCardStatementSchema = new mongoose.Schema({
  householdId: { type: String, required: true, index: true },
  cardId: { type: mongoose.Schema.Types.ObjectId, ref: 'CreditCard', required: true },
  statementDate: { type: Date, required: true },
  statementPeriodStart: { type: Date },
  statementPeriodEnd: { type: Date },
  totalAmount: { type: Number, default: 0 },
  charges: [{
    memberId: { type: String }, // userId of household member
    memberName: { type: String },
    amount: { type: Number, required: true },
    description: { type: String },
    transactionDate: { type: Date, default: Date.now },
    category: { type: String }, // from Plaid or manual entry
    source: { type: String, enum: ['plaid', 'manual'], default: 'manual' },
    verified: { type: Boolean, default: false }, // if auto-detected, needs manual verification
    overspendFlag: { type: Boolean, default: false }, // flagged during processing
    projectCreated: { type: mongoose.Schema.Types.ObjectId, ref: 'Project' } // link to autogenerated project
  }],
  submittedBy: { type: String }, // userId who submitted
  submittedAt: { type: Date, default: Date.now },
  processed: { type: Boolean, default: false },
  processedAt: { type: Date },
  createdAt: { type: Date, default: Date.now }
});

export default mongoose.model('CreditCardStatement', creditCardStatementSchema);
